services:
  db:
    image: postgres:latest
    container_name: pg-chat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_with_ai
    ports:
      - "5432:5432"

volumes:
  postgres_data:
